### ISSUE TITLE
Broken diagrams in Chrome browser

### ISSUE THREAD

**Issue by ejolie** [hackerwins/homepage-old#32]
**Description**
The diagrams in `docs` page look broken in Chrome browser/Mac OS. It's ok in Safari.
cf. (+) Same also in FireFox/Windows, Chrome/Windows, Edge/Windows (https://discordapp.com/channels/811798432041664532/934058117950488616/934319602249379890)

![image](https://user-images.githubusercontent.com/31282659/150625968-49eaec94-5921-4bb1-a599-74b85ed04214.png)
![image](https://user-images.githubusercontent.com/31282659/150625958-2b4710bd-0b75-4964-9c74-e44eb98564dc.png)

I attached a screenshot as it may have something to do with the browser font settings.
<img src="https://user-images.githubusercontent.com/31282659/150626378-faf25d21-76d4-4745-8fd1-942f6543bfb4.png" alt="image" width="600"/>

**Comment by lqez** [comment]
<img width="602" alt="Screen Shot 2022-01-22 at 10 13 33 PM" src="https://user-images.githubusercontent.com/579366/150639890-fa0c64be-f773-4953-96c8-f191fb6e6a0d.png">
I succeeded to regenerate the same problem by setting `monospace font` to non-monospace font.
This is basically not an issue of the Yorkie homepage style itself, but we can consider setting a custom monospace font to avoid these errors.

Thank you for reporting.

**Comment by easylogic** [comment]
It seems that this issue has not been resolved yet.

browser :  

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36

<img width="915" alt="스크린샷 2022-02-08 오후 12 22 24" src="https://user-images.githubusercontent.com/591983/152912810-9cea3283-8221-4fc8-9bf6-e23698781e2f.png">

**Comment by lqez** [comment]
@easylogic it looks like the appropriate font was not applied on your browser. We're using `Roboto Mono` for `<code>` block.
<img width="796" alt="Screen Shot 2022-02-08 at 5 31 01 PM" src="https://user-images.githubusercontent.com/579366/152948267-dc139329-dbfa-4241-be29-184233953f22.png">

Could you refresh your browser with clearing caches?

**Comment by easylogic** [comment]
hi. @lqez 

i was set dev tool to no-cache. 

<img width="1517" alt="스크린샷 2022-02-08 오후 11 01 08" src="https://user-images.githubusercontent.com/591983/153002292-dacc0aba-58b2-4d44-9441-146ea4b3705e.png">
