### ISSUE TITLE
yorkie demos didnt work

### ISSUE THREAD

**Issue by rebase** [hackerwins/homepage-old#47]
is this demo really working?
between two browsers, the only synchronized thing i checked is the user online number located at the top right
i think it has something problem 

![image](https://user-images.githubusercontent.com/50368758/174774263-23c3967e-8027-41bb-9425-0b47dab5e1ca.png)

**Comment by hackerwins** [comment]
@mihilt Thanks for your report.

This was fixed by https://github.com/yorkie-team/yorkie-team.github.io/commit/6bd89c711f605717a0d5cf756fc092c620cd7bda. Please clear the cache and check again.
